config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "application#index"
  get "/dashboard" => "application#dashboard"

  resources :customers do
    resources :order_rules
  end

  resources :orders

  resources :car_types do
    resources :car_models
  end

  resources :yards
  resources :tracks
  resources :trains
  post "/trains/spawn" => "trains#spawn_train"
  resources :local_trains
  resources :spawn_points
  resources :supply_train_blueprints

  mount Sidekiq::Web => '/dev/jobs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_model.rb
class CarModel < ApplicationRecord
    belongs_to :car_type

    validates :FQDN, presence: true
end

app/models/car_type.rb
class CarType < ApplicationRecord
    has_many :car_models, dependent: :destroy
    has_many :order_rules

    validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :order_rules, dependent: :destroy
    belongs_to :local_train
end

app/models/local_train.rb
# frozen_string_literal: true

class LocalTrain < ApplicationRecord
  belongs_to :yard
  has_many :customers
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_rule
  belongs_to :train, optional: true
  belongs_to :track, optional: true

  enum :status, [ :completed, :pending, :in_transit, :in_local_yard, :ready_for_delivery, :ready_for_setout ]
end

app/models/order_rule.rb
class OrderRule < ApplicationRecord
    belongs_to :customer
    belongs_to :car_type
    has_many :orders

    validates :max_cars, presence: true
    validates :manutention_time, presence: true
    validates :commodity, presence: true
end

app/models/spawn_point.rb
class SpawnPoint < ApplicationRecord
  belongs_to :track, optional: false
  has_many :supply_train_blueprints
end

app/models/track.rb
class Track < ApplicationRecord
    belongs_to :yard, optional: true
    has_one :train
    has_one :spawn_point
    has_many :orders

    validates :name, presence: true
    validates :length, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
    belongs_to :track, optional: true
    has_many :orders
end

app/models/yard.rb
class Yard < ApplicationRecord
    has_many :tracks
    has_many :local_trains
    belongs_to :yard, optional: true

    enum :yard_type, [ :local_yard, :classification_yard ]

    validates :name, presence: true
    validates :routing_tag, presence: true
    validates :yard_type, presence: true
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end

    def show
        @customer = Customer.find(params[:id])
    end

    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(customer_params)

        if @customer.save
            redirect_to customers_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @customer = Customer.find(params[:id])
    end

    def update
        @customer = Customer.find(params[:id])

        if @customer.update(customer_params)
            redirect_to customers_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @customer = Customer.find(params[:id])
        @customer.destroy

        redirect_to customers_path
    end

    private
    def customer_params
        params.require(:customer).permit(:name, :routing_tag, :destinations, :yard_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_types_helper.rb
module CarTypesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/local_trains_helper.rb
module LocalTrainsHelper
end

app/helpers/order_rules_helper.rb
module OrderRulesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/yards_helper.rb
module YardsHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer do |form| %>
<div class="mb-3">
    <%= form.label :name, { class: "form-label "} %>
    <%= form.text_field :name, { class: "form-control" } %>
    <% @customer.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

<div class="mb-3">
    <%= form.label :routing_tag, { class: "form-label "} %>
    <%= form.text_field :routing_tag, { class: "form-control" } %>
    <% @customer.errors.full_messages_for(:routing_tag).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

<div class="mb-3">
    <%= form.label :destinations, { class: "form-label "} %>
    <%= form.text_field :destinations, { class: "form-control" } %>
    <% @customer.errors.full_messages_for(:destinations).each do |message| %>
    <div><%= message %></div>
    <% end %>
</div>

  <div class="mb-3">
    <%= form.label :yard_id, "Local yard", { class: "form-label"} %>
    <%= form.collection_select :yard_id, Yard.local_yard.order(:name), :id, :name, { include_blank: true }, { class: "form-select" } %>
  </div>

<div>
    <%= form.submit class: "btn btn-primary mb-3" %>
</div>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit <%= @customer.name %></h1>

<%= render "form", customer: @customer %>

app/views/customers/index.html.erb
<div class="card">
  <h5 class="card-header">
    <span class="clearfix">
      <span class="text-uppercase">Customers</span>
      <%= link_to new_customer_path, { class: "float-end btn btn-primary" } do %>
        New
      <% end %>
    </span>
  </h5>

  <div class="card-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Local</th>
          <th>Yard</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.order(:name).each do |customer| %>
        <tr>
          <td><%= link_to "(#{customer.routing_tag}) #{customer.name}", customer_path(customer) %></td>
          <td><%= customer.local_train&.name %></td>
          <td><%= customer.local_train&.yard&.name %></td>
          <td><%= link_to "Delete", customer_path(customer), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          }%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/customers/new.html.erb
<div class="card">
  <h5 class="card-header">
    New Customer
  </h5>
  <div class="card-body">
    <%= render "form", customer: @customer %>
  </div>
</div>

app/views/customers/show.html.erb
<div class="card mb-3">
  <h5 class="card-header">
      <%= @customer.name %>
  </h5>
  <div class="card-body">

  </div>
</div>

<div class="card">
  <h5 class="card-header">
    <span>Order rules</span>
    <%= link_to new_customer_order_rule_path(@customer), { class: "float-end btn btn-primary" } do %>
      New
    <% end %>
  </h5>
  <div class="card-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Car type</th>
          <th>Commodity</th>
          <th>Capacity</th>
          <th>Current</th>
          <th>Dropoff (L/E)</th>
          <th>Manutention</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @customer.order_rules.each do |rule| %>
          <tr>
            <td><%= rule.car_type.name %></td>
            <td><%= rule.commodity %></td>
            <td><%= rule.max_cars %></td>
            <td><%= rule.orders.sum(:ordered_count) %></td>
            <td><%= rule.is_loaded ? "Loaded" : "Empty" %></td>
            <td><%= rule.manutention_time %>h</td>
            <td>
              <%= link_to "Edit", edit_customer_order_rule_path(@customer, rule) %>
              <%= link_to "Delete", customer_order_rule_path(@customer, rule), data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
              }%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p class="fs-7">
      Capacity = Maximum cars capacity allowed on the customer track<br />
      Current = Current cars on the track AND enroute
    </p>
  </div>
</div>