config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "application#index"
  get "/dashboard" => "application#dashboard"

  resources :customers do
    resources :order_rules
  end

  resources :orders

  resources :car_types do
    resources :car_models
  end

  resources :yards
  resources :tracks
  resources :trains
  post "/trains/spawn" => "trains#spawn_train"
  resources :local_trains
  resources :spawn_points
  resources :supply_train_blueprints

  mount Sidekiq::Web => '/dev/jobs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car_model.rb
class CarModel < ApplicationRecord
    belongs_to :car_type

    validates :FQDN, presence: true
end

app/models/car_type.rb
class CarType < ApplicationRecord
    has_many :car_models, dependent: :destroy
    has_many :order_rules

    validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :order_rules, dependent: :destroy
    belongs_to :local_train
end

app/models/local_train.rb
# frozen_string_literal: true

class LocalTrain < ApplicationRecord
  belongs_to :yard
  has_many :customers
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_rule
  belongs_to :train, optional: true
  belongs_to :track, optional: true

  enum :status, [ :completed, :pending, :in_transit, :in_local_yard, :ready_for_delivery, :ready_for_setout ]
end

app/models/order_rule.rb
class OrderRule < ApplicationRecord
    belongs_to :customer
    belongs_to :car_type
    has_many :orders

    validates :max_cars, presence: true
    validates :manutention_time, presence: true
    validates :commodity, presence: true
end

app/models/spawn_point.rb
class SpawnPoint < ApplicationRecord
  belongs_to :track, optional: false
  has_many :supply_train_blueprints
end

app/models/track.rb
class Track < ApplicationRecord
    belongs_to :yard, optional: true
    has_one :train
    has_one :spawn_point
    has_many :orders

    validates :name, presence: true
    validates :length, presence: true
end

app/models/train.rb
class Train < ApplicationRecord
    belongs_to :track, optional: true
    has_many :orders
end

app/models/yard.rb
class Yard < ApplicationRecord
    has_many :tracks
    has_many :local_trains
    belongs_to :yard, optional: true

    enum :yard_type, [ :local_yard, :classification_yard ]

    validates :name, presence: true
    validates :routing_tag, presence: true
    validates :yard_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end

    def turbo_visit(url, frame: nil, action: nil)
        options = {frame: frame, action: action}.compact
        turbo_stream.append_all("head") do
            helpers.javascript_tag(<<~SCRIPT.strip, nonce: true, data: {turbo_cache: false})
            window.Turbo.visit("#{helpers.escape_javascript(url)}", #{options.to_json})
            document.currentScript.remove()
            SCRIPT
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/car_types_helper.rb
module CarTypesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/order_rules_helper.rb
module OrderRulesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/yards_helper.rb
module YardsHelper
end

app/views/application/dashboard.html.erb
<%= render "application/partials/road_trains_overview" %>

app/views/application/index.html.erb
<h1>RailManager</h1>

<ul>
    <li><%= link_to "Customers", customers_path %></li>
    <li><%= link_to "Cars Type", car_types_path %></li>
    <li><%= link_to "Trains", trains_path %></li>
    <li><%= link_to "Yards", yards_path %></li>
    <li><%= link_to "Tracks", tracks_path %></li>
    <li><%= link_to "Orders", orders_path %></li>
    <li><%= link_to "Spawn points", spawn_points_path %></li>
    <li><%= link_to "Blueprints", supply_train_blueprints_path %></li>
</ul>

app/views/application/partials/_road_trains_overview.html.erb
<div class="card">
  <h5 class="card-header">
    <span class="clearfix">
      <span>ROAD TRAINS</span>
      <%= button_to trains_spawn_path, { form_class: "float-end", class: "btn btn-primary", data: { turbo: false } } do %>
        Request spawn <span class="badge text-bg-warning rounded-pill">1</span>
      <% end %>
    </span>
  </h5>
  <div class="card-body">

  </div>
</div>